import os
import io
import zipfile
from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from core.graph import app as workflow_app
from agents.legacy import legacy_analysis_agent


# 1. CRITICAL: Load the API Key FIRST
load_dotenv() 


app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class StoryInput(BaseModel):
    user_story: str

class LegacyInput(BaseModel):
    code_snippet: str
    
class CodeBundle(BaseModel):
    html_code: str
    css_code: str
    js_code: str
    backend_code: str
    database_schema: str

@app.post("/generate")
async def generate_app(data: StoryInput):
    print(f"Received Story: {data.user_story}")
    try:
        result = workflow_app.invoke({"user_story": data.user_story})
        return {
            "status": "success",
            # NEW KEYS
            "html_code": result.get("html_code"),
            "css_code": result.get("css_code"),
            "js_code": result.get("js_code"),
            # OLD KEYS
            "backend_code": result.get("backend_code"),
            "database_schema": result.get("database_schema"),
            "test_results": result.get("test_results")
        }
    except Exception as e:
        print(f"Error processing request: {e}")
        return {"status": "error", "message": str(e)}



@app.post("/analyze_legacy")
async def analyze_legacy(data: LegacyInput):
    try:
        analysis = legacy_analysis_agent(data.code_snippet)
        return {"status": "success", "analysis": analysis}
    except Exception as e:
        return {"status": "error", "message": str(e)}

@app.post("/download")
async def download_zip(data: CodeBundle):
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Frontend Files
        zip_file.writestr("public/index.html", data.html_code or "")
        zip_file.writestr("public/css/style.css", data.css_code or "")
        zip_file.writestr("public/js/script.js", data.js_code or "")
        
        # Backend Files
        zip_file.writestr("backend/main.py", data.backend_code or "")
        zip_file.writestr("database/schema.sql", data.database_schema or "")
        
        # Add a Readme
        zip_file.writestr("README.md", "# Generated by AutoForge\n\nTo run:\n1. Open index.html for frontend.\n2. Run `python backend/main.py` for backend.")

    zip_buffer.seek(0)
    
    return StreamingResponse(
        zip_buffer, 
        media_type="application/zip", 
        headers={"Content-Disposition": "attachment; filename=autoforge_project.zip"}
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)